FROM python:3.7
WORKDIR /app

COPY py_backend /app/py_backend
COPY app.py /app
COPY requirements.txt /app

RUN pip install -r ./requirements.txt

ENTRYPOINT [ "flask" ]

CMD ["run", "--host=0.0.0.0", "--port=5000"]