FROM python:3.7
WORKDIR /app

COPY py_backend /app/py_backend
COPY app.py /app
COPY requirements.txt /app

RUN pip install -r ./requirements.txt

CMD ["gunicorn","--workers=8", "--threads=12", "--bind=0.0.0.0:5000", "--forwarded-allow-ips=localhost", "app:app"]